// Subsets 寒蝉圆黑体 (Chill Round Gothic, SIL OFL 1.1) once per language, down to
// the characters that language's page uses, so ~9 MB per weight becomes ~100 kB
// and each visitor only downloads their own language's subset.
//
//   npm run fonts
//
// Run it after changing any Chinese/Japanese text; tests/fonts.test.js fails in CI
// when the text uses a character the committed subset doesn't contain.
// Source fonts are downloaded once into .cache/fonts (gitignored), pinned to a
// commit and checked by SHA-256.
import { createHash } from 'node:crypto';
import { existsSync, mkdirSync, readFileSync, writeFileSync, copyFileSync, rmSync, readdirSync } from 'node:fs';
import { join } from 'node:path';
import subsetFont from 'subset-font';
import { ROOT, MANIFEST_DIR, manifestPath, collectChars } from './font-chars.mjs';
import { LOCALES } from '../src/i18n/index.js';

const REPO = 'Warren2060/ChillRoundGothic';
const COMMIT = '53505f0818983d2fcdda00dc66e051ad13e81ffb';
const CACHE = join(ROOT, '.cache/fonts');
const OUT = join(ROOT, 'public/fonts');

// CSS weight → source file, sha256. Two weights keep the download small: CSS
// asking for 800 falls back to the 700 face, anything up to 500 to the 500 face.
const WEIGHTS = {
  500: ['ChillRoundGothic/ChillRoundGothic_Medium.otf', '401edab0771f03bd9a5fcdb51d9850c08ac2417c9dacc7843ac4dc6342838253'],
  700: ['ChillRoundGothic/ChillRoundGothic_Bold.otf', '7786713cbc1bde2ec2a4161fbb552e2a7d3e187737eeb581a48485d352a14caa'],
};
const LICENSE = ['License.txt', 'bdefa7c6496762298804550255762c4532124282910e976db960b24d04665ad4'];

const sha256 = (buf) => createHash('sha256').update(buf).digest('hex');

async function fetchPinned([path, hash]) {
  const file = join(CACHE, path.split('/').pop());
  if (!existsSync(file)) {
    const url = `https://raw.githubusercontent.com/${REPO}/${COMMIT}/${path}`;
    console.log(`downloading ${url}`);
    const res = await fetch(url);
    if (!res.ok) throw new Error(`${url}: HTTP ${res.status}`);
    writeFileSync(file, Buffer.from(await res.arrayBuffer()));
  }
  const buf = readFileSync(file);
  if (sha256(buf) !== hash) throw new Error(`${file}: checksum mismatch, delete it and rerun`);
  return file;
}

mkdirSync(CACHE, { recursive: true });
mkdirSync(OUT, { recursive: true });
// clear previous subsets so removed locales don't linger
for (const f of readdirSync(OUT)) if (f.endsWith('.woff2')) rmSync(join(OUT, f));

mkdirSync(MANIFEST_DIR, { recursive: true });
const sources = {};
for (const [weight, source] of Object.entries(WEIGHTS)) sources[weight] = readFileSync(await fetchPinned(source));

let css = `/* generated by scripts/build-fonts.mjs — do not edit */\n`;
for (const { code } of LOCALES) {
  const chars = collectChars(code);
  const sizes = [];
  for (const [weight, buf] of Object.entries(sources)) {
    const woff2 = await subsetFont(buf, chars, { targetFormat: 'woff2' });
    writeFileSync(join(OUT, `1xc-rounded-${code}-${weight}.woff2`), woff2);
    sizes.push(`${weight}: ${(woff2.length / 1024).toFixed(1)} kB`);
    const range = weight === '500' ? '100 500' : '600 900';
    css += `@font-face { font-family: "1xc Rounded ${code}"; src: url("/fonts/1xc-rounded-${code}-${weight}.woff2") format("woff2"); font-weight: ${range}; font-display: swap; }\n`;
  }
  css += `:root:lang(${code}) { --font-cjk: "1xc Rounded ${code}"; }\n`;
  writeFileSync(manifestPath(code), chars + '\n');
  console.log(`${code.padEnd(6)} ${String([...chars].length).padStart(4)} chars  ${sizes.join('  ')}`);
}
copyFileSync(await fetchPinned(LICENSE), join(OUT, 'OFL.txt'));
writeFileSync(join(ROOT, 'src/fonts.css'), css);
console.log('wrote src/fonts.css');
